require:
  - rubocop-rails

Metrics/LineLength:
  Max: 120

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'bin/setup'
    - 'bin/update'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature', 'scenario', 'let']
